language: python
dist: xenial
sudo: true
matrix:
  include:
    - python: 2.7
      env: RUN_COVERAGE=0
    - python: 3.5
      env: RUN_COVERAGE=1
    - python: 3.5-dev
      env: RUN_COVERAGE=0
    - python: 3.6
      env: RUN_COVERAGE=0
    - python: 3.6-dev
      env: RUN_COVERAGE=0
    - python: 3.7
      env: RUN_COVERAGE=0
    - python: 3.7-dev
      env: RUN_COVERAGE=0
install:
  - pip install -r requirements_dev.txt
script:
  - check-manifest
  - python setup.py sdist bdist_wheel
  - twine check dist/*
  - pip install -e .
  - python -c "import prism; prism.get_info()"
after_success:
  - |
    if [[ "$RUN_COVERAGE" == "1" ]]; then
      codecov
    fi
before_deploy:
    - rm -r dist
    - rm -r build
deploy:
    provider: pypi
    user: 1313e
    password:
        secure: "uovgLXvtHjkEARx+81EqX5aL32xInyK34uyxBhOTKNLfC6/OxM0DNr2jPYNwClCrSBe2Hrq2RsTqNI28SBtP7fn4sBk6SxKI1hI0PBWLoXWznOSv/LzN9W3QqzAXWmC1pFs1cPM+omzzAEMal9TISsF24boRFNBu/sVbkPwV3vW3ERjnLP84AhBUdn5gNxQXgBTMbuKKXFihEHIP18zHtOhY9dNwWpI/iNpV6zcIbPiitl697d9kjzqkB17fQvI9Fjej6pGJICRExwDvuEjPTiHpV13kBOjfvnoKnufxnmTFLBjoSO0v5Ec+ba1sLDi7qdzuT+YSEq9WmKfEaBJPa98slBZCrzAN1vyFToYGh94mUolI/QvaRKSjJu4SZRr0BLVTxykniMx9yddfesuMPmtintp9MK/OVuc76UAfwHtBGFRg+JTfFthyKSL5FNDKFcIKaOtkErVtZRs087AfmwV8bc/1veDJ5Zm+EwfavdhOLrHP4vRTpbbpYaA70jUbFtOQ5/uaYjbRQvvxgnPePkesst8KhzgYeDIJrplDIlmhSWEXO34k84mOKFXorPwA7bM+21MnUU1ER98Q+cIMbeKazH1isRyOtzJd8bhvXIO/tsA8rs9dByhCDmMoqJrXH1MRubdiQs3U4w+LO5bgJaP0h+RVllhgjOAphxFcBvI="
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
        branch: master
    
notifications:
  email: false
