language: python
os: linux
dist: xenial

env:
  global:
    - TWINE_USERNAME=1313e
    - secure: "b2AT80ISvAu1zr88zr/g7SrTqiynOXmrN3D8XBjs4+OlsNI5oBL079jQFztq2WaX/v6tYr8WKN13GZgGm07FH5xNDX/ezsbqh0aYOrKsmGiLPXxF+ZPiG15+KKHzvj3khb/1t4RoD+0cI/rn54+g+hQyeLLYohQcbgsmdChygdjsdBIdQWE7/mU/hV4Qy6RtxgcP/pJEeuUlh5KtDVta1c3YodVK/sL0SGQx3neVOA8UWFl3F1LUd/lcP0ikG24A/MeBx5U/EtQtl5OiVqaS7AEOHUHYvNBr7Ge/g9opMCUUtPk4nazOxEL5T+uRhrSFEil5B1YzC+EufMZzN3DyjyRJFepIZrqtqlUDh46zFEXyxKP3xzgSFL3+XcooX15QQcDVlaasVdQMuryg2fvsi5AoSpJNpTioR6epGXWeSP7FcZ+dw14oWmNoievS2zGD0rVqkHiTI8bj/m2fvdpISmSjtcyYp45NSBjl+bEjmlIpquZLTIZcHgDUzA76FPTmpDYv6vBq+gNOfdV0PflWgNact48Xk2Z/M7U7fCTIdYvhSy7uGuDVLzkmTjKp7+gjXyRtaokVlYkW6QLIOb7afl9Md4y+l0EhewnG2jtx5Aq0hRLZ3yyundHCyZV6k/YpwSFdKxSO7xPgdSCl+BT3WAvLCGjTxQzfsauSN/mQ8tw="

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      language: generic
      env: PY=3
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev
  allow_failures:
    - python: 3.8-dev

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -y xvfb libdbus-1-3 libxkbcommon-x11-0
      export QT_QPA_PLATFORM=offscreen
    fi
  - python$PY -m pip install --upgrade pip setuptools wheel
  - pip$PY install -r requirements_dev.txt
install:
  - check-manifest
  - python$PY setup.py sdist bdist_wheel
  - twine check dist/*
  - python$PY -c "import prism; prism.get_info()"
script:
  - coverage run --rcfile=setup.cfg -m pytest
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -y -q openmpi-bin libopenmpi-dev
    else
      brew install openmpi
    fi
  - pip$PY --no-cache-dir install mpi4py
  - |
    mpiexec -n 2 coverage run --rcfile=setup.cfg -m mpi4py -m pytest
    coverage combine
    coverage report -m
after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_BRANCH" == "dev" ]]; then
      echo "Hello"
    fi
    
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7027496921d111b98149
    on_success: change
    on_failure: always
  email:
    recipients:
      - secure: "s4U/OU0NPFvJkbvdVTBsaSu45TFD27bIOuowv4cvaV28KR1K3ma9ho3mv9+j6+T9hWR95BI+/nAfLA9QAm8T05ePYSKaNCdLwiCbihsLoNo8isa+14xdHZAj/txGpYQQX7ayL8/uJxi6bSiRxuJBKshpZKswdLL3tS4fXAH0RvoaJVSlQqLpiFhiXZogn+Uk23MawdlYB/swPNX/97BXd8xcMpj/UzjBKjOhPGWr9JcCY0ec9mgtgrQjWr8XsgQdjda1c0++HrBfZcHb5M0Y5JECkpMgQr/d42CdQCO+XgG/RAMUE/WWmsYq8YWrbZinLWs21JRNWemDa9I15Vvio8ZgAjCIAj92ij9tOyYfG9Hx5cIkc4fupn3ImwA/naw+yk1n7qT1YjHbFHkAHfWd8dqNCGCF1EB1+O5hlAWj2K7bzZEX9T/Bwxja3jchBM2/ENmZ5qmvhxSpQ/YnhTOMrZiEUBU1cQLPs3mpcOQiVcG4+3vZeFNKOOWJciRSutBr4xzkORNwBfkRatyDufLBgtaSFe++1wjQ36QDaMC+kwiZGs56Jo94fA05X9rOw31cS9RsY2vUMW4BwyiAQMg8RdvaDRh1nPCsomd3nPyvwrvvKb/KGecr76OMRlYWwreAOah5kz6QcXEQ3CtFo/FMm1S50L6gKtgFQergL3fpgPc="
    on_success: change
    on_failure: always
