language: python
dist: xenial
sudo: true
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.5-dev
    - python: 3.6
    - python: 3.6-dev
    - python: 3.7
    - python: 3.7-dev
install:
  - pip install -r requirements_dev.txt
  - export OMP_NUM_THREADS=1
script:
  - check-manifest --ignore appveyor.cmd,.appveyor.yml,.codecov.yml,prism_trash*,docs*,joss_paper*
  - python setup.py sdist bdist_wheel
  - twine check dist/*
  - pip install -e .
  - coverage run --rcfile=setup.cfg -p -m py.test prism
  - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
  - pip --no-cache install mpi4py
  - mpiexec -n 2 coverage run --rcfile=setup.cfg -p -m mpi4py -m py.test prism
after_script:
  - coverage combine
  - coverage report -m
after_success:
  - codecov -t 6a194e41-c88d-4b7e-af10-29d9f54f8d84
notifications:
  email: false
